name = "wesworld-frontend"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
PAYLOAD_API_URL = "https://wesworld-cms-production.up.railway.app"